//! Regenerates `fixtures/zfp/` — the committed `nd_zfp` stream pins.
//!
//! ```bash
//! cargo run -p ndic-zfp --example gen_fixtures --features serde
//! ```
//!
//! Two files, both byte-stability gates (regenerate only on a deliberate
//! format bump):
//!
//! - `checksums.json` — FNV-1a 64 checksums of the encoded stream across
//!   the dims × dtype × mode matrix (`tests/checksums.rs` reproduces it).
//! - `tiny-chunk-4x8x8-rate8.zfp` — a pinned fixed-rate chunk the Rust and
//!   Python tests re-encode byte-for-byte.

use std::path::Path;

include!("../tests/common/mod.rs");

fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/zfp");
    std::fs::create_dir_all(&dir).expect("fixtures/zfp");

    let mut cases = Vec::new();
    for (shape, dtype, config) in matrix_cases() {
        let n: usize = shape.iter().product();
        let chunk = ramp_chunk(n, dtype);
        let zdtype = ndic_zfp::ZfpDtype::from_zarr_name(dtype).expect("matrix dtype");
        let stream = ndic_zfp::encode_chunk(&chunk, &shape, zdtype, &config).expect("encode");
        cases.push(serde_json::json!({
            "shape": shape,
            "dtype": dtype,
            "configuration": serde_json::to_value(&config).expect("config"),
            "bytes": stream.len(),
            "fnv1a64": format!("{:#018x}", fnv1a64(&stream)),
        }));
    }
    let doc = serde_json::json!({
        "$comment": "Generated by `cargo run -p ndic-zfp --example gen_fixtures --features serde` \
                     — pins nd_zfp stream bytes (full ZFP header + payload) across the \
                     dims × dtype × mode matrix over the ramp_chunk fixture field. \
                     Regenerate only on a deliberate format bump.",
        "cases": cases,
    });
    let path = dir.join("checksums.json");
    std::fs::write(
        &path,
        serde_json::to_string_pretty(&doc).expect("json") + "\n",
    )
    .expect("write checksums");
    println!("wrote {}", path.display());

    let config = ndic_zfp::NdZfpConfig {
        mode: "fixed_rate".into(),
        rate: Some(8.0),
        dims: Some(3),
        ..Default::default()
    };
    let stream = ndic_zfp::encode_chunk(
        &tiny_chunk_f32(),
        &[4, 8, 8],
        ndic_zfp::ZfpDtype::F32,
        &config,
    )
    .expect("encode");
    let path = dir.join("tiny-chunk-4x8x8-rate8.zfp");
    std::fs::write(&path, &stream).expect("write chunk fixture");
    println!("wrote {} ({} bytes)", path.display(), stream.len());
}
