"""Tests for the release scripts in `scripts/release/`.

These three scripts decide what version number reaches crates.io, PyPI, and
npm, and none of it is reversible — a published version cannot be replaced or
re-uploaded. That makes their failure modes unusually expensive for how little
code they are, and unusually hard to notice: `set-version.py` rewrites seven
file formats with text substitution, so the way it breaks is by *quietly*
matching the wrong line or missing one, and `publish-crates.py` decides which
crates to skip from a registry query that can fail in four different ways.

Everything that touches the filesystem runs against a synthetic repository
built in a temporary directory, never the real one. `set-version.py` locates
the repository root as `parents[2]` of its own path, so copying it to
`<tmp>/scripts/release/set-version.py` retargets it — which also means the real
`scripts/ci/check-package-versions.py` can be copied in alongside and used as
the oracle, exactly as it is in production.

Run with:

    uvx --with pytest --from pytest pytest scripts/tests -q

Requires: pytest. No network — the one script that talks to crates.io has its
transport replaced.
"""

from __future__ import annotations

import importlib.util
import json
import pathlib
import shutil
import subprocess
import sys
import textwrap
import types
import urllib.error

import pytest

REPO = pathlib.Path(__file__).resolve().parents[2]
RELEASE = REPO / "scripts" / "release"

# The fixture repository is deliberately *not* a copy of this one: it is the
# smallest tree that exercises every branch, including the two cases the real
# workspace does not currently have (a member pinning a literal version, and a
# `publish = false` member) and the one it must never lose (a third-party
# `"version"` key in package-lock.json that has to stay put).
FIXTURE_VERSION = "0.4.2"

CARGO_TOML = """\
[workspace]
resolver = "2"
members = [
    "crates/alpha",
    "crates/beta",
    "crates/nopub",
]

[workspace.package]
version = "0.4.2"
edition = "2024"

[workspace.dependencies]
# --- Internal crates -------------------------------------------------
alpha = { path = "crates/alpha", version = "0.4.2" }
# Key order reversed on purpose: the rewriter must not assume `path` first.
beta = { version = "0.4.2", path = "crates/beta" }
# A path dep with no version is intentional for unpublished members.
nopub = { path = "crates/nopub" }

# --- Third party ------------------------------------------------------
serde = { version = "1", features = ["derive"] }
"""

CARGO_LOCK = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "alpha"
version = "0.4.2"
dependencies = [
 "serde",
]

[[package]]
name = "beta"
version = "0.4.2"
dependencies = [
 "alpha",
]

[[package]]
name = "nopub"
version = "0.4.2"

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
"""

PYPROJECT = """\
[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "nd-image-codecs"
version = "0.4.2"
requires-python = ">=3.11"

[tool.maturin]
# A `version` key in another table must not be mistaken for the project's.
python-source = "python"
"""

INIT_PY = '''\
"""Package init."""

__all__ = ["__version__"]

try:
    __version__: str = _native_version()
except ImportError:
    __version__ = "0.4.2"
'''


def _member_manifest(name: str, *, literal_version: bool = False, publish: bool = True) -> str:
    version = f'version = "{FIXTURE_VERSION}"' if literal_version else "version.workspace = true"
    lines = ["[package]", f'name = "{name}"', version]
    if not publish:
        lines.append("publish = false")
    return "\n".join(lines) + "\n"


def _package_json(name: str) -> dict:
    return {"name": name, "version": FIXTURE_VERSION, "license": "MIT"}


def _package_lock() -> dict:
    return {
        "name": "@fideus-labs/nd-image-codecs",
        "version": FIXTURE_VERSION,
        "lockfileVersion": 3,
        "packages": {
            "": {"name": "@fideus-labs/nd-image-codecs", "version": FIXTURE_VERSION},
            # The property that matters most in this file: a third-party pin
            # that shares the key name and must not move.
            "node_modules/typescript": {"version": "5.6.0"},
            "node_modules/vitest": {"version": "2.0.0"},
        },
    }


def _write_json(path: pathlib.Path, document: dict) -> None:
    path.write_text(json.dumps(document, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


@pytest.fixture
def fake_repo(tmp_path: pathlib.Path) -> pathlib.Path:
    """A minimal repository the release scripts accept, at `FIXTURE_VERSION`."""
    root = tmp_path / "repo"
    (root / "scripts" / "release").mkdir(parents=True)
    (root / "scripts" / "ci").mkdir(parents=True)

    for script in ("set-version.py", "publish-crates.py"):
        shutil.copy2(RELEASE / script, root / "scripts" / "release" / script)
    # The oracle, copied verbatim: these tests assert the writer and the
    # production reader agree, not that the writer agrees with a restatement
    # of itself.
    shutil.copy2(
        REPO / "scripts" / "ci" / "check-package-versions.py",
        root / "scripts" / "ci" / "check-package-versions.py",
    )

    (root / "Cargo.toml").write_text(CARGO_TOML, encoding="utf-8")
    (root / "Cargo.lock").write_text(CARGO_LOCK, encoding="utf-8")
    for name, literal, publish in (("alpha", False, True), ("beta", True, True), ("nopub", False, False)):
        crate = root / "crates" / name
        crate.mkdir(parents=True)
        (crate / "Cargo.toml").write_text(
            _member_manifest(name, literal_version=literal, publish=publish), encoding="utf-8"
        )

    py = root / "bindings" / "python" / "nd-image-codecs"
    (py / "python" / "nd_image_codecs").mkdir(parents=True)
    (py / "pyproject.toml").write_text(PYPROJECT, encoding="utf-8")
    (py / "python" / "nd_image_codecs" / "__init__.py").write_text(INIT_PY, encoding="utf-8")

    ts = root / "bindings" / "typescript"
    ts.mkdir(parents=True)
    _write_json(ts / "package.json", _package_json("@fideus-labs/nd-image-codecs"))
    _write_json(ts / "package-lock.json", _package_lock())

    js = root / "bindings" / "javascript"
    js.mkdir(parents=True)
    _write_json(js / "package.json", _package_json("nd-image-codecs"))

    return root


def run_set_version(repo: pathlib.Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(repo / "scripts" / "release" / "set-version.py"), *args],
        capture_output=True,
        text=True,
        check=False,
    )


def load(path: pathlib.Path, name: str) -> types.ModuleType:
    """Import a script whose filename is not a valid module name."""
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# --------------------------------------------------------------- parse-tag.py


@pytest.mark.parametrize(
    ("tag", "version", "prerelease", "npm_tag"),
    [
        ("v0.2.0", "0.2.0", "false", "latest"),
        ("v1.0.0", "1.0.0", "false", "latest"),
        ("v0.0.0", "0.0.0", "false", "latest"),
        ("v10.20.30", "10.20.30", "false", "latest"),
        ("v1.0.0-rc.1", "1.0.0-rc.1", "true", "next"),
        ("v0.2.0-alpha", "0.2.0-alpha", "true", "next"),
        ("v2.0.0-beta.11", "2.0.0-beta.11", "true", "next"),
    ],
)
def test_parse_tag_accepts_release_tags(tag, version, prerelease, npm_tag, tmp_path):
    output = tmp_path / "github-output"
    result = subprocess.run(
        [sys.executable, str(RELEASE / "parse-tag.py"), tag],
        capture_output=True,
        text=True,
        check=False,
        env={"PATH": "/usr/bin:/bin", "GITHUB_OUTPUT": str(output)},
    )
    assert result.returncode == 0, result.stderr
    written = dict(line.split("=", 1) for line in output.read_text().splitlines())
    assert written == {
        "version": version,
        "tag": tag,
        "prerelease": prerelease,
        "npm-tag": npm_tag,
    }


@pytest.mark.parametrize(
    "tag",
    [
        "v0.2",  # not three components
        "v0.2.0.1",  # four
        "0.2.0",  # no `v`
        "vendor-bump",  # matches the `v*` trigger, is not a release
        "v2-experiment",
        "v1.2.3+build",  # legal SemVer; unpublishable on PyPI and npm
        "v1.2.3-rc.1+build",
        "v01.2.3",  # leading zero
        "v1.2.3 ",  # stray whitespace is stripped, then still fine — see below
        "",
        "v",
        "vx.y.z",
    ],
)
def test_parse_tag_rejects_everything_else(tag, tmp_path):
    output = tmp_path / "github-output"
    result = subprocess.run(
        [sys.executable, str(RELEASE / "parse-tag.py"), tag],
        capture_output=True,
        text=True,
        check=False,
        env={"PATH": "/usr/bin:/bin", "GITHUB_OUTPUT": str(output)},
    )
    if tag.strip() == "v1.2.3":
        # Surrounding whitespace is stripped rather than rejected; a tag cannot
        # contain it, but a shell can add it.
        assert result.returncode == 0
        return
    assert result.returncode == 2, f"{tag!r} was accepted: {result.stdout}"
    assert not output.exists(), "a rejected tag must not write workflow outputs"


def test_parse_tag_prints_without_github_output():
    """The script is also a human-readable check, run by hand on a tag."""
    result = subprocess.run(
        [sys.executable, str(RELEASE / "parse-tag.py"), "v3.1.4"],
        capture_output=True,
        text=True,
        check=False,
        env={"PATH": "/usr/bin:/bin"},
    )
    assert result.returncode == 0
    assert "3.1.4" in result.stdout
    assert "latest" in result.stdout


# ------------------------------------------------------------- set-version.py


def test_set_version_writes_every_location(fake_repo):
    result = run_set_version(fake_repo, "1.5.0")
    assert result.returncode == 0, result.stderr

    # The production reader is the assertion: it parses all seven files from
    # scratch and fails if any of the 23 literals disagrees.
    assert "all " in result.stdout and "read 1.5.0" in result.stdout

    manifest = (fake_repo / "Cargo.toml").read_text()
    assert 'version = "1.5.0"' in manifest
    assert 'alpha = { path = "crates/alpha", version = "1.5.0" }' in manifest
    assert 'beta = { version = "1.5.0", path = "crates/beta" }' in manifest
    # A path dep with no `version` stays that way — adding one would make the
    # crate unpublishable.
    assert 'nopub = { path = "crates/nopub" }' in manifest
    # A third-party requirement is not a version literal to bump.
    assert 'serde = { version = "1", features = ["derive"] }' in manifest

    # A member that spells out its own version rather than inheriting.
    assert 'version = "1.5.0"' in (fake_repo / "crates" / "beta" / "Cargo.toml").read_text()
    assert "version.workspace = true" in (fake_repo / "crates" / "alpha" / "Cargo.toml").read_text()

    assert '__version__ = "1.5.0"' in (
        fake_repo / "bindings/python/nd-image-codecs/python/nd_image_codecs/__init__.py"
    ).read_text()


def test_set_version_leaves_third_party_lock_pins_alone(fake_repo):
    """The failure this guards is silent and total.

    `Cargo.lock` and `package-lock.json` are mostly third-party pins that share
    the key name being rewritten. Moving one produces a lockfile that resolves
    to a version that does not exist.
    """
    assert run_set_version(fake_repo, "2.0.0").returncode == 0

    lock = (fake_repo / "Cargo.lock").read_text()
    assert 'name = "serde"\nversion = "1.0.219"' in lock
    assert lock.count('version = "2.0.0"') == 3  # alpha, beta, nopub — and nothing else
    assert lock.startswith("# This file is automatically @generated by Cargo.")

    npm_lock = json.loads((fake_repo / "bindings/typescript/package-lock.json").read_text())
    assert npm_lock["version"] == "2.0.0"
    assert npm_lock["packages"][""]["version"] == "2.0.0"
    assert npm_lock["packages"]["node_modules/typescript"]["version"] == "5.6.0"
    assert npm_lock["packages"]["node_modules/vitest"]["version"] == "2.0.0"


def test_set_version_preserves_comments_and_layout(fake_repo):
    """These files are hand-maintained and heavily commented.

    A `tomllib`-plus-serializer round trip would reflow all of it, which is why
    the rewriter is textual.
    """
    before = (fake_repo / "Cargo.toml").read_text()
    assert run_set_version(fake_repo, "0.9.1").returncode == 0
    after = (fake_repo / "Cargo.toml").read_text()

    assert "# --- Internal crates" in after
    assert "# Key order reversed on purpose" in after
    assert "# A path dep with no version is intentional" in after
    assert before.count("\n") == after.count("\n")
    assert after.splitlines()[0] == "[workspace]"

    pyproject = (fake_repo / "bindings/python/nd-image-codecs/pyproject.toml").read_text()
    assert "# A `version` key in another table must not be mistaken" in pyproject
    assert 'requires = ["maturin>=1.7,<2.0"]' in pyproject


def test_set_version_json_files_keep_npm_formatting(fake_repo):
    """npm rewrites any file it does not recognize, so the bytes have to match."""
    assert run_set_version(fake_repo, "0.9.1").returncode == 0
    for relative in (
        "bindings/typescript/package.json",
        "bindings/typescript/package-lock.json",
        "bindings/javascript/package.json",
    ):
        text = (fake_repo / relative).read_text()
        assert text.endswith("}\n"), relative
        assert '\n  "version"' in text or '\n      "version"' in text, relative
        assert json.dumps(json.loads(text), indent=2, ensure_ascii=False) + "\n" == text


@pytest.mark.parametrize("version", ["1.0.0-rc.1", "0.2.0-alpha.3", "2.0.0-beta"])
def test_set_version_accepts_prereleases(fake_repo, version):
    result = run_set_version(fake_repo, version)
    assert result.returncode == 0, result.stderr
    assert f"read {version}" in result.stdout


def test_set_version_from_tag_strips_the_v(fake_repo):
    assert run_set_version(fake_repo, "--from-tag", "v3.2.1").returncode == 0
    assert '[workspace.package]\nversion = "3.2.1"' in (fake_repo / "Cargo.toml").read_text()


def test_set_version_from_tag_requires_the_v(fake_repo):
    result = run_set_version(fake_repo, "--from-tag", "3.2.1")
    assert result.returncode == 2
    assert "does not start with 'v'" in result.stderr


@pytest.mark.parametrize(
    "version",
    ["1.2", "1.2.3.4", "v1.2.3", "1.2.3+build", "01.2.3", "", "latest", "1.2.3-"],
)
def test_set_version_rejects_unpublishable_versions(fake_repo, version):
    original = (fake_repo / "Cargo.toml").read_text()
    result = run_set_version(fake_repo, version)
    assert result.returncode == 2, f"{version!r} was accepted"
    assert "SemVer" in result.stderr
    # Validation happens before the first write, so a bad argument leaves the
    # tree untouched rather than half-stamped.
    assert (fake_repo / "Cargo.toml").read_text() == original


def test_set_version_reports_a_moved_pyproject_layout(fake_repo):
    pyproject = fake_repo / "bindings/python/nd-image-codecs/pyproject.toml"
    pyproject.write_text(
        textwrap.dedent(
            """\
            [build-system]
            requires = ["maturin>=1.7,<2.0"]

            [project]
            name = "nd-image-codecs"
            """
        ),
        encoding="utf-8",
    )
    result = run_set_version(fake_repo, "1.5.0")
    assert result.returncode == 1
    assert "no [project] version found" in result.stderr
    assert "check-package-versions.py" in result.stderr


def test_set_version_refuses_to_reformat_a_hand_edited_json_file(fake_repo):
    """Rewriting it would produce a whole-file diff nobody asked for."""
    target = fake_repo / "bindings/javascript/package.json"
    target.write_text(json.dumps(_package_json("nd-image-codecs"), indent=4) + "\n", encoding="utf-8")
    before = target.read_text()

    result = run_set_version(fake_repo, "1.5.0")
    assert result.returncode == 1
    assert "does not round-trip" in result.stderr
    assert target.read_text() == before


def test_set_version_reports_a_member_missing_from_the_lockfile(fake_repo):
    lock = fake_repo / "Cargo.lock"
    lock.write_text(
        lock.read_text().replace('[[package]]\nname = "nopub"\nversion = "0.4.2"\n', ""),
        encoding="utf-8",
    )
    result = run_set_version(fake_repo, "1.5.0")
    assert result.returncode == 1
    assert "nopub" in result.stderr


def test_set_version_no_verify_skips_the_oracle(fake_repo):
    """`--no-verify` exists for callers that run the check themselves."""
    (fake_repo / "scripts" / "ci" / "check-package-versions.py").unlink()
    result = run_set_version(fake_repo, "1.5.0", "--no-verify")
    assert result.returncode == 0, result.stderr
    assert 'version = "1.5.0"' in (fake_repo / "Cargo.toml").read_text()


def test_set_version_is_idempotent(fake_repo):
    assert run_set_version(fake_repo, "1.5.0").returncode == 0
    snapshot = {p: p.read_bytes() for p in fake_repo.rglob("*") if p.is_file()}
    assert run_set_version(fake_repo, "1.5.0").returncode == 0
    assert {p: p.read_bytes() for p in fake_repo.rglob("*") if p.is_file()} == snapshot


# ---------------------------------------------------------- publish-crates.py


@pytest.fixture
def publish_crates(fake_repo) -> types.ModuleType:
    """`publish-crates.py`, imported with its REPO pointing at the fixture."""
    return load(fake_repo / "scripts" / "release" / "publish-crates.py", "publish_crates_fixture")


def test_publishable_members_skips_publish_false(publish_crates):
    """`cargo publish --workspace` skips them, so the registry queries must too."""
    assert publish_crates.publishable_members() == [
        ("alpha", "crates/alpha"),
        ("beta", "crates/beta"),
    ]


def _fake_urlopen(payload=None, *, status=None, error=None, body=None):
    """Stand in for `urllib.request.urlopen`.

    `payload` is serialized as the response body; `status` raises an HTTPError;
    `error` raises it directly; `body` returns raw bytes that may not be JSON.
    """
    class Response:
        def read(self):
            return body if body is not None else json.dumps(payload).encode()

        def __enter__(self):
            return self

        def __exit__(self, *exc):
            return False

    def opener(request, timeout=None):
        if error is not None:
            raise error
        if status is not None:
            raise urllib.error.HTTPError(request.full_url, status, "boom", {}, None)
        return Response()

    return opener


def test_published_versions_reads_the_registry(publish_crates, monkeypatch):
    monkeypatch.setattr(
        publish_crates.urllib.request,
        "urlopen",
        _fake_urlopen({"versions": [{"num": "0.1.0"}, {"num": "0.2.0"}]}),
    )
    assert publish_crates.published_versions("alpha") == {"0.1.0", "0.2.0"}


def test_published_versions_treats_404_as_unclaimed(publish_crates, monkeypatch):
    monkeypatch.setattr(publish_crates.urllib.request, "urlopen", _fake_urlopen(status=404))
    assert publish_crates.published_versions("brand-new") == set()


@pytest.mark.parametrize(
    "kwargs",
    [
        {"status": 500},
        {"status": 403},
        {"error": urllib.error.URLError("no route to host")},
        {"error": TimeoutError()},
        {"body": b"<html>we are down</html>"},
        # Parseable JSON, successful status, no `versions` key — an API change
        # or an error body served with the wrong status. The tempting default
        # is an empty set, which reads as "the name is free".
        {"payload": {"errors": [{"detail": "Not Found"}]}},
        {"payload": {}},
    ],
)
def test_published_versions_never_guesses_on_failure(publish_crates, monkeypatch, kwargs):
    """Read as "not published", any of these sends cargo at a live version.

    That fails the release for a reason unrelated to the code, so the query has
    to raise instead of returning an empty set.
    """
    monkeypatch.setattr(publish_crates.urllib.request, "urlopen", _fake_urlopen(**kwargs))
    with pytest.raises(publish_crates.RegistryError):
        publish_crates.published_versions("alpha")


def _capture_cargo(module, monkeypatch) -> list[list[str]]:
    calls: list[list[str]] = []

    def fake_run(command, **kwargs):
        calls.append(command)
        return subprocess.CompletedProcess(command, 0)

    monkeypatch.setattr(module.subprocess, "run", fake_run)
    return calls


def test_publish_skips_entirely_when_everything_is_published(publish_crates, monkeypatch, capsys):
    monkeypatch.setattr(publish_crates, "published_versions", lambda crate: {"1.0.0"})
    calls = _capture_cargo(publish_crates, monkeypatch)
    monkeypatch.setattr(sys, "argv", ["publish-crates.py", "1.0.0"])

    assert publish_crates.main() == 0
    assert calls == [], "cargo must not run when there is nothing to upload"
    assert "nothing to do" in capsys.readouterr().out


def test_publish_excludes_only_the_crates_already_uploaded(publish_crates, monkeypatch):
    """The re-run path: cargo aborts the whole workspace on the first one."""
    monkeypatch.setattr(
        publish_crates, "published_versions", lambda crate: {"1.0.0"} if crate == "alpha" else set()
    )
    calls = _capture_cargo(publish_crates, monkeypatch)
    monkeypatch.setattr(sys, "argv", ["publish-crates.py", "1.0.0"])

    assert publish_crates.main() == 0
    assert calls == [["cargo", "publish", "--workspace", "--locked", "--exclude", "alpha"]]


def test_publish_uses_the_plain_workspace_command_on_a_fresh_version(publish_crates, monkeypatch):
    monkeypatch.setattr(publish_crates, "published_versions", lambda crate: set())
    calls = _capture_cargo(publish_crates, monkeypatch)
    monkeypatch.setattr(sys, "argv", ["publish-crates.py", "1.0.0"])

    assert publish_crates.main() == 0
    assert calls == [["cargo", "publish", "--workspace", "--locked"]]


def test_publish_dry_run_verifies_the_whole_workspace(publish_crates, monkeypatch):
    """`--dry-run` downgrades "already exists" to a warning.

    Excluding the published crates would mean the release's verification job
    silently stopped checking them.
    """
    monkeypatch.setattr(publish_crates, "published_versions", lambda crate: {"1.0.0"})
    calls = _capture_cargo(publish_crates, monkeypatch)
    monkeypatch.setattr(sys, "argv", ["publish-crates.py", "1.0.0", "--dry-run"])

    assert publish_crates.main() == 0
    assert calls == [["cargo", "publish", "--workspace", "--locked", "--dry-run"]]


def test_publish_reports_a_registry_failure_without_running_cargo(publish_crates, monkeypatch, capsys):
    def explode(crate):
        raise publish_crates.RegistryError("could not reach crates.io")

    monkeypatch.setattr(publish_crates, "published_versions", explode)
    calls = _capture_cargo(publish_crates, monkeypatch)
    monkeypatch.setattr(sys, "argv", ["publish-crates.py", "1.0.0"])

    assert publish_crates.main() == 1
    assert calls == []
    assert "could not reach crates.io" in capsys.readouterr().err


def test_publish_propagates_a_cargo_failure(publish_crates, monkeypatch):
    monkeypatch.setattr(publish_crates, "published_versions", lambda crate: set())

    def fake_run(command, **kwargs):
        return subprocess.CompletedProcess(command, 101)

    monkeypatch.setattr(publish_crates.subprocess, "run", fake_run)
    monkeypatch.setattr(sys, "argv", ["publish-crates.py", "1.0.0"])
    assert publish_crates.main() == 101


# ------------------------------------------------------------ cross-script


def test_the_two_semver_grammars_agree():
    """`parse-tag.py` gates the workflow; `set-version.py` gates every other
    caller. A tag the first accepts and the second rejects would fail a release
    after the gates had passed."""
    parse_tag = load(RELEASE / "parse-tag.py", "parse_tag_module")
    set_version = load(RELEASE / "set-version.py", "set_version_module")
    assert parse_tag.SEMVER.pattern == set_version.SEMVER.pattern
